version: "3.3"
services:
  pg_master:
    image: lucasfs/pg-pi_master
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=testdb
      - PG_REP_USER=rep
      - PG_REP_PASSWORD=postgres
    volumes:
      - /mnt/storage/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - pg-net
    deploy:
      placement:
        constraints:
        - node.labels.type == primary
  
  pg_slave:
    image: lucasfs/pg-pi_slave
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=testdb
      - PG_REP_USER=rep
      - PG_REP_PASSWORD=postgres
      - PG_MASTER_HOST=pg_master
    volumes:
      - /mnt/storage/pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - pg-net
    
    deploy:
      placement:
        constraints:
        - node.labels.type == worker

networks:
  pg-net:
    external:
      name: pgnet 

